---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-sa-{{ .Values.clusterName }}
  namespace: {{ .Values.infraCluster.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync-role-{{ .Values.clusterName }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
  resourceNames: ["{{ .Values.secretsSource.sourceSecret }}"]
  namespaces: ["{{ .Values.secretsSource.sourceNamespace }}"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
  namespaces: ["{{ .Values.infraCluster.namespace }}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-sync-reader-{{ .Values.clusterName }}
  namespace: {{ .Values.secretsSource.sourceNamespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["{{ .Values.secretsSource.sourceSecret }}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-sync-reader-binding-{{ .Values.clusterName }}
  namespace: {{ .Values.secretsSource.sourceNamespace }}
subjects:
- kind: ServiceAccount
  name: secret-sync-sa-{{ .Values.clusterName }}
  namespace: {{ .Values.infraCluster.namespace }}
roleRef:
  kind: Role
  name: secret-sync-reader-{{ .Values.clusterName }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-sync-writer-{{ .Values.clusterName }}
  namespace: {{ .Values.infraCluster.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-sync-writer-binding-{{ .Values.clusterName }}
  namespace: {{ .Values.infraCluster.namespace }}
subjects:
- kind: ServiceAccount
  name: secret-sync-sa-{{ .Values.clusterName }}
  namespace: {{ .Values.infraCluster.namespace }}
roleRef:
  kind: Role
  name: secret-sync-writer-{{ .Values.clusterName }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-sync-job-{{ .Values.clusterName }}
  namespace: {{ .Values.infraCluster.namespace }}
spec:
  ttlSecondsAfterFinished: {{ .Values.secretSync.ttlSecondsAfterFinished }}
  template:
    metadata:
      name: secret-sync-job-{{ .Values.clusterName }}
    spec:
      serviceAccountName: secret-sync-sa-{{ .Values.clusterName }}
      restartPolicy: OnFailure
      containers:
      - name: secret-sync
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          echo "Fetching source secret from {{ .Values.secretsSource.sourceNamespace }} namespace..."
          
          # Get the pullSecret value
          PULL_SECRET=$(kubectl get secret {{ .Values.secretsSource.sourceSecret }} \
            -n {{ .Values.secretsSource.sourceNamespace }} \
            -o jsonpath='{.data.pullSecret}' | base64 -d)
          
          # Get the ssh-publickey value
          SSH_PUBLIC_KEY=$(kubectl get secret {{ .Values.secretsSource.sourceSecret }} \
            -n {{ .Values.secretsSource.sourceNamespace }} \
            -o jsonpath='{.data.ssh-publickey}' | base64 -d)
          
          echo "Creating pullsecret-cluster-{{ .Values.clusterName }} secret..."
          
          # Create pullsecret-cluster-{{ .Values.clusterName }} secret
          kubectl create secret generic pullsecret-cluster-{{ .Values.clusterName }} \
            --namespace={{ .Values.infraCluster.namespace }} \
            --from-literal='.dockerconfigjson'="$PULL_SECRET" \
            --type=kubernetes.io/dockerconfigjson \
            --dry-run=client -o yaml | kubectl apply -f -
          
          echo "Creating sshkey-cluster-{{ .Values.clusterName }} secret..."
          
          # Create sshkey-cluster-{{ .Values.clusterName }} secret
          kubectl create secret generic sshkey-cluster-{{ .Values.clusterName }} \
            --namespace={{ .Values.infraCluster.namespace }} \
            --from-literal='id_rsa.pub'="$SSH_PUBLIC_KEY" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          echo "Secret sync completed successfully!"
